SELECT * FROM DBA_DDL_LOCKS WHERE name ='P_TEST';

SELECT * FROM DBA_DDL_LOCKS WHERE name ='P_KREDIT';

SELECT * FROM DBA_DDL_LOCKS WHERE name ='P_PROFIL';


DECLARE
a varchar2(200);
begin
  a:=P_TEST.FILIAL(234);
  DBMS_LOCK.SLEEP(5);
  
end;  
